In [22]:
import numpy as np
import pandas as pd

import os

In [5]:
pwd

'C:\\Users\\Rokib\\python_program'

In [28]:
df = pd.read_csv(r'C:\Users\Rokib\OneDrive\Documents\dataset\data\Corona_tweets.csv')
df

,User_name,Time,Location,text
0,1,16-03-2020,London,@MeNyrbie @Phil_Gahan @Chrisitv https://t.co/i...
1,2,16-03-2020,UK,advice Talk to your neighbours family to excha...
2,3,16-03-2020,Vagabonds,Coronavirus Australia: Woolworths to give elde...
3,4,16-03-2020,NaN,My food stock is not the only one which is emp...
4,5,16-03-2020,NaN,"Me, ready to go at supermarket during the #COV..."
...,...,...,...,...
41152,41153,14-04-2020,"Wellington City, New Zealand",Airline pilots offering to stock supermarket s...
41153,41154,14-04-2020,NaN,Response to complaint not provided citing COVI...
41154,41155,14-04-2020,NaN,You know its getting tough when @KameronWilds...
41155,41156,14-04-2020,NaN,Is it wrong that the smell of hand sanitizer i...
41156,41157,14-04-2020,i love you so much || he/him,@TartiiCat Well new/used Rift S are going for ...

In [27]:
df.Location.value_counts()

London                            540
United States                     528
London, England                   520
New York, NY                      395
Washington, DC                    373
                                 ...
Ciutadà de República catalana       1
Lexington/Phoenix                   1
113 camden Rd, Tunbridge wells      1
Farnborough, England                1
Gazing at Mt Baker.                 1
Name: Location, Length: 12220, dtype: int64

In [29]:
import re
def clean_tweets(text):
    text =re.sub("RT @[\w]*:","",text)
    text =re.sub("@[\w]*","",text)
    text =re.sub("https?://[A-Za-z0-9./]*","",text)
    text =re.sub("\n","",text)
    return text

In [30]:
df['text']=df['text'].apply(lambda x: clean_tweets(x))

In [33]:
df.head(50)

,User_name,Time,Location,text
0,1,16-03-2020,London,and and
1,2,16-03-2020,UK,advice Talk to your neighbours family to excha...
2,3,16-03-2020,Vagabonds,Coronavirus Australia: Woolworths to give elde...
3,4,16-03-2020,NaN,My food stock is not the only one which is emp...
4,5,16-03-2020,NaN,"Me, ready to go at supermarket during the #COV..."
5,6,16-03-2020,"ÜT: 36.319708,-82.363649",As news of the regions first confirmed COVID-...
6,7,16-03-2020,"35.926541,-78.753267",Cashier at grocery store was sharing his insig...
7,8,16-03-2020,Austria,Was at the supermarket today. Didn't buy toile...
8,9,16-03-2020,"Atlanta, GA USA",Due to COVID-19 our retail store and classroom...
9,10,16-03-2020,"BHAVNAGAR,GUJRAT","For corona prevention,we should stop to buy th..."
10,11,16-03-2020,"Makati, Manila",All month there hasn't been crowding in the su...
11,12,16-03-2020,"Pitt Meadows, BC, Canada","Due to the Covid-19 situation, we have increas..."
12,13,16-03-2020,Horningsea,#horningsea is a caring community. Lets ALL l...
13,14,16-03-2020,"Chicago, IL","Me: I don't need to stock up on food, I'll jus..."
14,15,16-03-2020,NaN,ADARA Releases COVID-19 Resource Center for Tr...
15,16,16-03-2020,"Houston, Texas",Lines at the grocery store have been unpredict...
16,17,16-03-2020,Saudi Arabia,????? ????? ????? ????? ??\r\r?????? ????? ???...
17,18,16-03-2020,"Ontario, Canada",16MAR20 Russia consumer surveillance watchdog...
18,19,16-03-2020,North America,"Amazon Glitch Stymies Whole Foods, Fresh Groce..."
19,20,16-03-2020,"Denver, CO","For those who aren't struggling, please consid..."
20,21,16-03-2020,southampton soxx xxx,with 100 nations inficted with covid 19 th...
21,22,16-03-2020,Global,\r\r\r\rThe COVID-19 coronavirus pandemic is i...
22,23,16-03-2020,NaN,We have AMAZING CHEAP DEALS! FOR THE #COVID201...
23,24,16-03-2020,NaN,We have AMAZING CHEAP DEALS! FOR THE #COVID201...
24,25,16-03-2020,Downstage centre,what is being done to ensure food and other ...
25,26,16-03-2020,London,UK #consumer poll indicates the majority expec...
26,27,16-03-2020,"Ketchum, Idaho",In preparation for higher demand and a potenti...
27,28,16-03-2020,Everywhere You Are!,This morning I tested positive for Covid 19. I...
28,29,16-03-2020,"New York, NY",Do you see malicious price increases in NYC? T...
29,30,16-03-2020,"Someplace, USA",Soon with dwindling supplies unlawful Panicky...
30,31,16-03-2020,NaN,There Is of in the Country The more empty she...
31,32,16-03-2020,NaN,'Hole' Foods...\r\r\r\r...images from the nice...
32,33,16-03-2020,"Markham, Ontario",Retail store closures could explode because of...
33,34,16-03-2020,"Virginia, USA",Coronavirus fun fact: if you cough at the groc...
34,35,16-03-2020,"London, England",We're sorry to say that our event is being ca...
35,36,16-03-2020,Sverige,Went to the supermarket yesterday and the toil...
36,37,16-03-2020,Where The Wild Things Are,"Yes, buy only what you need.\r\r\r\rBut what's..."
37,38,16-03-2020,Canada,Worried about the impact of the current COVID-...
38,39,16-03-2020,NaN,my wife works retail&amp;a customer came in ye...
39,40,16-03-2020,United States,Now I can go to the supermarket like this with...
40,41,16-03-2020,"Fort Worth, Texas",We're here to provide a safe shopping experien...
41,42,16-03-2020,NaN,"Curious, do we think retail shoppers will do ..."
42,43,16-03-2020,Houston,CHECK VIDEO ?? ??No food ? in USA market due ...
43,44,16-03-2020,"Vancouver, British Columbia",Breaking Story: Online clothes shopping rises ...
44,45,16-03-2020,NaN,This is the line outside in as customers wa...
45,46,16-03-2020,Midrand,"South Africans stock up on food, basic goods a..."
46,47,16-03-2020,Drogheda,Please Share Know someone who s 65 Living on...
47,48,16-03-2020,"Columbia, MO",People posting and sharing photos of of half t...
48,49,16-03-2020,"Arkansas, USA","Never thought I'd say this, but. 2019, Will yo..."
49,50,16-03-2020,"Washington, DC",COVID-19 restrictions sparking a run on cannab...

In [1]:
pwd

'C:\\Users\\Rokib\\python_program'

In [4]:
pd.starttls

NameError: name 'pd' is not defined